import "./globals.css";
import StoreProvider from "./StoreProvider";
import I18nProvider from "./I18nProvider";
import { ToastProvider } from "@/contexts/ToastContext";
import ClientAuthProvider from "@/components/ClientAuthProvider";

export const metadata = {
  title: "Project",
  description: "Generated by ....",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <ClientAuthProvider>
          <StoreProvider>
            <I18nProvider>
              <ToastProvider>
                {children}
              </ToastProvider>
            </I18nProvider>
          </StoreProvider>
        </ClientAuthProvider>
      </body>
    </html>
  );
}
